

// Déclaration des tableaux contenant les listes des mots proposés à l'utilisateur
const listeMots = [
  // Héros Disney
  "Mickey Mouse",
  "Minnie",
  "Donald",
  "Dingo",
  "Pluto",
  "Blanche Neige",
  "Cendrillon",
  "Ariel",
  "Belle",
  "Mulan",
  "Pocahontas",
  "Elsa",
  "Anna",
  "Olaf",
  "Simba",
  "Nala",
  "Rafiki",
  "Timon",
  "Pumbaa",
  "Baloo",
  "Bagheera",
  "Aladdin",
  "Jasmine",
  "Génie",
  "Hercule",
  "Megara",
  "Tarzan",
  "Jane Porter",
  "Peter Pan",
  "Clochette",
  "Capitaine Crochet",
  "Winnie",
  "Porcinet",
  "Tigrou",
  "Stitch",
  "Lilo",
  "Baymax",
  "Hiro",
  "Raya",
  "Moana",
  "Maui",
  "Asha",
  "Miguel",
  "Hector",
  "Ernesto de la Cruz",
  "Flash McQueen",
  "Sally Carrera",
  "Doc Hudson",
  "Woody",
  "Buzz l'Éclair",
  "Jessie",
  "Sully",
  "Bob Razowski",
  "Boo",
  "Nemo",
  "Dory",
  "Marin",
  "Remy",
  "Linguini",
  "Carl Fredricksen",
  "Russell",
  "Dug",
  "Joy",
  "Tristesse",
  "Colère",
  "Peureux",
  "Dégoût",
  "Mirabel",
  "Isabela",
  "Luisa",
  "Jim Hawkins",
  "Jack Sparrow",
  "Tiana",
  "Naveen",
  "Elsa la Reine des Neiges"
];

const listePhrases = [
  // Citations cultes Disney & Pixar
  "Hakuna Matata",
  "Quand on prie la bonne étoile",
  "Vers l'infini et au-delà",
  "Il en faut peu pour être heureux",
  "Rêve ta vie en couleur, c’est le secret du bonheur",
  "L’aventure est là dehors",
  "Les rires sont éternels, l’imagination n’a pas d’âge",
  "Libérée, délivrée",
  "Je voudrais déjà être roi",
  "Rester, c’est exister. Voyager, c’est vivre",
  "Le passé peut faire mal, mais on peut soit fuir, soit en tirer une leçon",
  "Je ne suis pas une princesse, je suis une guerrière",
  "L’amour est une porte ouverte",
  "On ne voit bien qu’avec le cœur",
  "Être courageux, ce n’est pas ne pas avoir peur, c’est avancer malgré la peur",
  "Souviens-toi de qui tu es",
  "Ohana signifie famille",
  "Partir là-bas",
  "Un homme libre",
  "Il faut battre le fer tant qu’il est chaud",
  "Si tu peux le rêver, tu peux le faire",
  "Les rêves sont faits pour être réalisés",
  "Je peux voler !",
  "Les souvenirs font de nous ce que nous sommes",
  "Les amis ne mentent jamais",
  "La famille avant tout",
  "Ne laisse personne te dire que tu ne peux pas",
  "Ce n’est pas parce qu’on est petit qu’on ne peut pas être grand",
  "Chaque fin est un nouveau départ",
  "Le courage, c’est de dire la vérité"
];
